### Load in NumPy (remember to pip install numpy first)

In [2]:
import numpy as np

### The Basics

In [3]:
# initialiaze an array (dtype is optional)
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get Dimension
a.ndim

1

In [6]:
# Get Shape (rows, cols)
b.shape

(2, 3)

In [7]:
# Get Type
a.dtype

dtype('int32')

In [8]:
# Get Size
a.itemsize

4

In [9]:
# Get total size
a.nbytes

12

In [10]:
# Get number of elements
a.size

# total size is therfore then nbytes * size

3

### Accessing/Changing specific elements, rows, columns, etc

In [11]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
# Get a specific element [r, c] (0 indexed)
a[1, 5]

13

In [21]:
# Get a specific row (a[0] would also work)
a[0, :]

array([1, 2, 1, 4, 5, 6, 7])

In [14]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [24]:
# Getting a little more fancy → [startindex:endindex:stepsize]
# gets 2nd, 4th, and, and 6th cols in first row
a[0, 1:-1:2]

array([2, 4, 6])

In [26]:
# replacing specifc value
a[1,5] = 20

# replacing column
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [17]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
# Get specific element (work outside in)
b[0,1,1]

4

In [28]:
# replace (as long as dimension is the same on each side of = this will work)
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


### Initializing Different Types of Arrays

In [30]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [ ]:
# Any other number (in this case using the number 99)
np.full((2,2), 99)

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [ ]:
# full_like() defines matrix based on shape of an already existing matrix
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.07805642, 0.53385716],
       [0.02494273, 0.99955252],
       [0.48588042, 0.91247437],
       [0.27779213, 0.16597751]])

In [ ]:
# Random Integer values
# where -4 and 8 are the start and end numbers
np.random.randint(-4,8, size=(3,3))

array([[-2, -4, -4],
       [ 6,  6,  3],
       [ 3,  2,  2]])

In [ ]:
# The identity matrix
# only needs one param bc identity matrix is a square matrix by nature
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [32]:
# initiliazes 5x5 array of all 1s
output = np.ones((5,5))
print(output)
print('\n')

# initilizes 3x3 array of all 0s
z = np.zeros((3,3))
# sets middle element in 3x3 array to 9
z[1,1] = 9
print(z)
print('\n')

# updates middle of 5x5 to be the z array
output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [33]:
# need to use copy() to copy values between arrays
# otherwise if just b = a then the two arrays will be allocated the same spot in memory and when one updates so will the other
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


### Mathematics

In [35]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [37]:
# element wise arithmetic
a + 2

array([3, 4, 5, 6])

In [38]:
a - 2

array([-1,  0,  1,  2])

In [39]:
a * 2

array([2, 4, 6, 8])

In [40]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [41]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [42]:
a ** 2

array([ 1,  4,  9, 16])

In [43]:
# Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [ ]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [44]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

# cols of first matrix a need to be equal to rows of second matrix b for matrix multiplication

# matrix multiplication → (1x1x1) x (2x2x2)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [55]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
# get minimum of array
np.min(stats)

1

In [56]:
# get max of each row (axis=1)
np.max(stats, axis=1)


array([3, 6])

In [ ]:
# sums by column (axis=0)
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [58]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

# reshaping array (just needs to have the same amount of values)
after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [ ]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [61]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

print(h1)
print(h2)
np.hstack((h1,h2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [63]:
filedata = np.genfromtxt('data.txt', delimiter=',')

# can specify datatype
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [64]:
# Boolean masking
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [65]:
# filter only where > 50
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [ ]:
# use ~ for not
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [80]:
# Practicing generating an array and making specific value calls
a = np.array([1,2,3,4,5])
b = a + 5
c = b + 5
d = c + 5
e = d + 5
f = e + 5

x = np.vstack([a, b, c, d, e, f])
print(x)
print('\n')

x1 = x[2:4, 0:2]
print(x1)
print('\n')

x2 = x[[0,1,2,3], [1,2,3,4]]
print(x2)
print('\n')

x3 = x[[0,4,5], 3:]
print(x3)
print('\n')

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


[[11 12]
 [16 17]]


[ 2  8 14 20]


[[ 4  5]
 [24 25]
 [29 30]]


